global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'sfarmanian@gmail.com'
  smtp_auth_username: 'sfarmanian@gmail.com'
  smtp_auth_password: '****'

route:
  receiver: email-notifications

receivers:
  - name: email-notifications
    email_configs:
      - to: 'farmaniansaribeg@gmail.com'
